name: Environment variable practice

on:
    workflow_dispatch:

env:
    WORKFLOW_ENV_VAR: "Workflow level env variable"

jobs:
    Build1:
        runs-on: ubuntu-latest
        env:
            JOB_ENV_VAR: "Job level env variable"
        steps:
            - name: Build1 variables
              env:
                STEP_ENV_VAR: "Step level env variable"
              run: |
                echo "B1_WORKFLOW_LEVEL_ENV_VAR: $WORKFLOW_ENV_VAR"
                echo "B1_JOB_LEVEL_ENV_VAR: $JOB_ENV_VAR"
                echo "B1_STEP_LEVEL_ENV_VAR: $STEP_ENV_VAR"
    
    Build2:
        runs-on: ubuntu-latest
        steps:
            - name: Build2 variables
              run: |
                echo "B2_WORKFLOW_LEVEL_ENV_VAR: $WORKFLOW_ENV_VAR"
                echo "B2_JOB_LEVEL_ENV_VAR: $JOB_ENV_VAR"
                echo "B2_STEP_LEVEL_ENV_VAR: $STEP_ENV_VAR"
    

